# -*- coding: utf-8 -*-
"""Aplikasi Prediksi Harga Rumah di Tebet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SF1f0jHjW98KjWr7IwcxEAQVQVJzUUqk

# Aplikasi Prediksi Harga Rumah di Tebet.

## Import library yang dibutuhkan
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"""## Import Data

Data berasal dari dataset kaggle :
https://www.kaggle.com/datasets/wisnuanggara/daftar-harga-rumah/data
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("wisnuanggara/daftar-harga-rumah")

print("Path to dataset files:", path)

import os
df = pd.read_excel(os.path.join(path, 'DATA RUMAH.xlsx'))
df.head()

"""## Data Preprocessing"""

df.info()
print("Shape of data:")
print(df.shape)

print("Jumlah data duplicated:", df.duplicated().sum(), end="")
df.isna().sum()

df = df.rename(columns={
    'NO': 'nomor',
    'NAMA RUMAH': 'nama_rumah',
    'HARGA': 'harga',
    'LB': 'lb',
    'LT': 'lt',
    'KT': 'kt',
    'KM': 'km',
    'GRS': 'grs'
})
df

#Mengganti satuan harga agar lebih readable
df['harga'] = (df['harga']/1000000).astype(int)
df.drop(columns=['nomor'], inplace=True)
df.head()

q1 = df['harga'].quantile(0.25)
median = df['harga'].median()
q3 = df['harga'].quantile(0.75)

def classification_harga(harga):
    if harga <= q1:
        return 'Murah'
    elif harga <= median:
        return 'Menengah'
    else:
        return 'Mahal'

# Menambahkan kolom baru 'Klasifikasi Harga'
df['tingkat_harga'] = df['harga'].apply(classification_harga)

# Menampilkan DataFrame dengan kolom baru
df.head()

df.describe()

"""Dari fungsi `.describe()` di atas, kita dapat melihat beberapa statistik penting tentang kolom harga:

- **Harga Terendah**: 430 juta
- **Quartil 25% (Q1)**: 3.2 miliar
- **Median**: 5 miliar
- **Quartil 75% (Q3)**: 9 miliar
- **Harga Termahal**: 65 miliar

Selain itu, kita juga dapat mengamati bahwa semua kolom atau data yang digunakan, kecuali kolom nama_rumah, memiliki korelasi yang positif dengan harga.

## Eksplorasi Data
"""

plt.figure(figsize=(12, 8))
plt.subplot(2, 3, 1)
sns.histplot(df['harga'], kde=True)
plt.title('Distribusi Harga')

plt.subplot(2, 3, 2)
sns.histplot(df['lb'], kde=True)
plt.title('Distribusi Luas Bangunan')

plt.subplot(2, 3, 3)
sns.histplot(df['lt'], kde=True)
plt.title('Distribusi Luas Tanah')

plt.subplot(2, 3, 4)
sns.histplot(df['kt'], kde=True)
plt.title('Distribusi Jumlah Kamar Tidur')

plt.subplot(2, 3, 5)
sns.histplot(df['km'], kde=True)
plt.title('Distribusi Jumlah Kamar Mandi')

plt.subplot(2, 3, 6)
sns.histplot(df['grs'], kde=True)
plt.title('Distribusi Jumlah Garasi')
plt.show()

# Menghapus kolom 'tingkat_harga' dan 'daerah'
df_corr = df.drop(['tingkat_harga','nama_rumah'], axis=1)

# Menghitung matriks korelasi
correlation_all = df_corr.corr()

# Menampilkan matriks korelasi
plt.figure(figsize=(6, 4))
sns.heatmap(correlation_all, annot=True, cmap='rocket', fmt=".2f")
plt.title('Matriks Korelasi')
plt.show()

plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='tingkat_harga', order=['Murah', 'Menengah', 'Mahal'], palette='rocket')
plt.title('Jumlah rumah dalam Setiap Kategori Harga')
plt.xlabel('Kategori Harga')
plt.ylabel('Jumlah Rumah')
plt.show()

df['tingkat_harga'].value_counts()

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor # Added this line
import warnings
warnings.filterwarnings('ignore')
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
            print(os.path.join(dirname, filename))

            # You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
            # You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"""## Pemodelan dan Evaluasi
### Persiapan Data untuk Pemodelan
"""

X = df[['lb','lt','kt','km','grs']].values #Feature
y = df['harga'].values #Target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

"""## Model Regresi Linear Berganda"""

y_train_pred = model.predict(X_train)
y_pred = model.predict(X_test)

# Menghitung MAE, MSE, dan R2 Score untuk data pelatihan
mae_train = mean_absolute_error(y_train, y_train_pred)
mse_train = mean_squared_error(y_train, y_train_pred)
r2_train = r2_score(y_train, y_train_pred)

# Menghitung MAE, MSE, dan R2 Score untuk data pengujian
mae_test = mean_absolute_error(y_test, y_pred)
mse_test = mean_squared_error(y_test, y_pred)
r2_test = r2_score(y_test, y_pred)

# Menampilkan hasil evaluasi
print("Evaluasi Model pada Data Pelatihan:")
print(f'MAE: {mae_train}')
print(f'MSE: {mse_train}')
print(f'R2 Score: {r2_train}')
print("\nEvaluasi Model pada Data Pengujian:")
print(f'MAE: {mae_test}')
print(f'MSE: {mse_test}')
print(f'R2 Score: {r2_test}')

"""## Regularisasi"""

# Regularisasi dengan model Ridge
model_ridge = make_pipeline(StandardScaler(), Ridge(alpha=0.1))
model_ridge.fit(X_train, y_train)

# Evaluasi model Ridge
y_train_pred_ridge = model_ridge.predict(X_train)
y_pred_ridge = model_ridge.predict(X_test)
mae_train_ridge = mean_absolute_error(y_train, y_train_pred_ridge)
mse_train_ridge = mean_squared_error(y_train, y_train_pred_ridge)
r2_train_ridge = r2_score(y_train, y_train_pred_ridge)
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("Evaluasi Model Ridge pada Data Pelatihan:")
print(f'MAE: {mae_train_ridge}')
print(f'MSE: {mse_train_ridge}')
print(f'R2 Score: {r2_train_ridge}')
print("\nEvaluasi Model Ridge pada Data Pengujian:")
print(f'MAE: {mae_ridge}')
print(f'MSE: {mse_ridge}')
print(f'R2 Score: {r2_ridge}')

# Visualisasi regresi untuk data latih dan data uji
plt.figure(figsize=(10, 6))

# Plot data latih
plt.scatter(y_train, y_train_pred, color='orange', label='Data Latih')

# Plot data uji
plt.scatter(y_test, y_pred, color='red', label='Data Uji')

# Plot garis identitas
plt.plot([min(y_train), max(y_train)], [min(y_train), max(y_train)], linestyle='--', color='gray', label='Garis Identitas')

# Label sumbu x dan y
plt.xlabel('Nilai Sebenarnya')
plt.ylabel('Nilai Prediksi')

# Judul plot
plt.title('Prediksi Model Regresi Linier')

# Menambahkan legenda
plt.legend()

# Menampilkan plot
plt.show()

rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

import ipywidgets as widgets
from IPython.display import display

# Definisikan fungsi untuk memprediksi harga berdasarkan fitur yang dipilih
def predict_house_price(lb, lt, kt, km, grs):
    # Lakukan prediksi harga menggunakan model regresi linier
    predicted_price = model.predict([[lb, lt, kt, km, grs]])

    # Tampilkan hasil prediksi
    print("Harga rumah impian anda diperkirakan sekitar IDR {:,.3f} juta".format(predicted_price[0]))

# Buat slider untuk setiap fitur
slider_lb = widgets.FloatSlider(value=100, min=df['lb'].min(), max=df['lb'].max(), step=10, description='LB:')
slider_lt = widgets.FloatSlider(value=300, min=20, max=df['lt'].max(), step=10, description='LT:')
slider_kt = widgets.FloatSlider(value=3, min=1, max=df['kt'].max(), step=1, description='KT:')
slider_km = widgets.FloatSlider(value=2, min=1, max=df['km'].max(), step=1, description='KM:')
slider_grs = widgets.FloatSlider(value=2, min=1, max=df['grs'].max(), step=1, description='GRS:')

# Buat tampilan interaktif
widgets.interactive(predict_house_price, lb=slider_lb, lt=slider_lt, kt=slider_kt, km=slider_km, grs=slider_grs)

"""## Model Regresi Random Forest"""

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_train_pred_rf = rf_model.predict(X_train)
y_test_pred_rf = rf_model.predict(X_test)

mae_train_rf = mean_absolute_error(y_train, y_train_pred_rf)
mse_train_rf = mean_squared_error(y_train, y_train_pred_rf)
r2_train_rf = r2_score(y_train, y_train_pred_rf)

mae_test_rf = mean_absolute_error(y_test, y_test_pred_rf)
mse_test_rf = mean_squared_error(y_test, y_test_pred_rf)
r2_test_rf = r2_score(y_test, y_test_pred_rf)

print("=== Random Forest Regressor ===")
print("Train:")
print(f"MAE  : {mae_train_rf}")
print(f"MSE  : {mse_train_rf}")
print(f"R2   : {r2_train_rf}")

print("\nTest:")
print(f"MAE  : {mae_test_rf}")
print(f"MSE  : {mse_test_rf}")
print(f"R2   : {r2_test_rf}")

importances = rf_model.feature_importances_
features = ['lb','lt','kt','km','grs']

for f, imp in zip(features, importances):
    print(f"{f}: {imp:.3f}")


plt.figure(figsize=(7,4))
plt.barh(features, importances)
plt.xlabel("Importance")
plt.title("Feature Importance (Random Forest)")
plt.show()

def eval_regression(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    return mae, mse, rmse, r2

# ====== 1) Linear Regression ======
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
mae_lr, mse_lr, rmse_lr, r2_lr = eval_regression(y_test, y_pred_lr)

# ====== 2) Random Forest Regressor ======
rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
mae_rf, mse_rf, rmse_rf, r2_rf = eval_regression(y_test, y_pred_rf)

# ====== Tabel perbandingan ======
results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest Regressor"],
    "MAE (lebih kecil lebih baik)": [mae_lr, mae_rf],
    "RMSE (lebih kecil lebih baik)": [rmse_lr, rmse_rf],
    "R2 (lebih besar lebih baik)": [r2_lr, r2_rf],
})

results

# Train score (cek overfitting)
train_pred_lr = lr.predict(X_train)
train_pred_rf = rf.predict(X_train)

mae_lr_tr, mse_lr_tr, rmse_lr_tr, r2_lr_tr = eval_regression(y_train, train_pred_lr)
mae_rf_tr, mse_rf_tr, rmse_rf_tr, r2_rf_tr = eval_regression(y_train, train_pred_rf)

results_train_test = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest Regressor"],
    "R2 Train": [r2_lr_tr, r2_rf_tr],
    "R2 Test":  [r2_lr, r2_rf],
    "RMSE Train": [rmse_lr_tr, rmse_rf_tr],
    "RMSE Test":  [rmse_lr, rmse_rf],
})

results_train_test

import pandas as pd

metrics_df = pd.DataFrame({
    "Metric": ["MAE", "MSE", "R2"],
    "Linear Regression": [mae_lr, mse_lr, r2_lr],
    "Random Forest": [mae_rf, mse_rf, r2_rf]
})

metrics_df

import matplotlib.pyplot as plt
import numpy as np

models = ["Linear Regression", "Random Forest Regressor#"]
metrics = ["MAE", "MSE", "R²"]

values = [
    [mae_lr, mae_rf],
    [mse_lr, mse_rf],
    [r2_lr, r2_rf]
]

colors = plt.cm.viridis(np.linspace(0.2, 0.8, len(models)))

plt.figure(figsize=(14,4))

for i, metric in enumerate(metrics):
    plt.subplot(1,3,i+1)
    plt.bar(models, values[i], color=colors)
    plt.title(f"Perbandingan {metric}")
    plt.grid(axis="y", alpha=0.3)

    if metric == "R²":
        plt.ylim(0,1)

plt.tight_layout()
plt.show()

"""Nilai MAE, MSE, dan R² yang divisualisasikan diperoleh dari hasil prediksi pada data uji (test set). Hal ini bertujuan untuk mengevaluasi kemampuan generalisasi model terhadap data yang belum pernah dilihat sebelumnya.

Evaluasi pada data latih digunakan sebagai pembanding untuk mengidentifikasi potensi overfitting.

## Deployment Menggunakan Regresi Random Forest
"""

import joblib

# Pastikan ini model RF yang mau kamu deploy
# rf = RandomForestRegressor(...); rf.fit(X_train, y_train)

joblib.dump(rf, "rf_house_price.pkl")
print("Model tersimpan: rf_house_price.pkl")

import gradio as gr
import joblib
import numpy as np

model = joblib.load("rf_house_price.pkl")

def format_rupiah(x: int) -> str:
    # format 2311499339 -> "Rp 2.311.499.339"
    return "Rp {:,}".format(x).replace(",", ".")

def predict_price(lb, lt, kt, km, grs):
    X = np.array([[lb, lt, kt, km, grs]], dtype=float)
    pred_juta = model.predict(X)[0]          # output: satuan juta
    pred_rupiah = int(round(pred_juta * 1_000_000))  # jadi rupiah
    return format_rupiah(pred_rupiah)

demo = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.Number(label="LB (Luas Bangunan)", value=100),
        gr.Number(label="LT (Luas Tanah)", value=200),
        gr.Number(label="KT (Kamar Tidur)", value=3),
        gr.Number(label="KM (Kamar Mandi)", value=2),
        gr.Number(label="GRS (Garasi)", value=1),
    ],
    outputs=gr.Textbox(label="Hasil Prediksi"),
    title="Prediksi Harga Rumah - Random Forest",
)

if __name__ == "__main__":
    demo.launch()